### ISSUE TITLE
Implement incremental download

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/GN2PG#1]
La mise en place de la mise à jour incrémentale des données requiert des modifications à GeoNature avec l'ajout d'une journalisation des données modifiées en synthèse dont les modalités restent à définir.

* Une journalisation généralisée unique simple avec triggers indiquant pour chaque donnée le type de mise à jour (Delete, Insert, Update) et le timestamp de la modification. Scénario intéressant à court terme, performant côté source mais potentiellement lourd côté client en cas d'importante mise à jour. 
* Une journalisation plus poussée avec mention de l'export concerné (id_export) mais qui peut avoir des conséquences en termes de performances car nécessite, avant action sur la donnée en synthèse, d'identifier les exports concernés.

Cette journalisation nécessite également la mise à disposition, côté GeoNature source, d'une API spécifique consultable par intervalles de temps (début/fin avec un delta par défaut, ex. 10 jours, à définir en option?.

Il pourra être intéressant de définir un pas de temps limite de conservation de l'historique pour ne pas surcharger la bdd.

**Comment by camillemonchicourt** [comment]
Je me demande si on doit aller jusqu'à une journalisation des données dans la synthèse.
Au moins pour les création et les mises à jour, il suffirait d'utiliser le champs ``date_update`` dans la synthèse pour identifier les données ajoutées ou modifiées depuis le dernier import.

A ma connaissance c'est ce qu'on fait dans d'autres outils d'import automatique des données.
Il faut peut-être seulement ajouter la possibilité de filtrer un export avec ce champs (liste toutes les données de la synthèse dont date_update est supérieure à la date de mon dernier import).

Reste à voir le cas des suppressions. 
Dans certains outils, on compare les données de la destination pour voir si elles ne sont plus dans la source.
Dans GeoNature avec des centaines de milliers de données, cela serait certainement trop long et lourd. Mais à creuser si une solution ne sera pas viable sans tout journaliser ? Ou alors ne journaliser que les suppressionns ?

**Comment by lpofredc** [comment]
Oui, pour les données de type synthese, j'envisagerai bien deux fonctionnements, selon les actions appliquées sur la synthèse.
* Pour les INSERT/UPDATE fournir une API fournissant simplement `id_synthese`, `uuid`, `last_action` en se basant `meta_create_date` et `meta_update_date` de la synthèse,  idéalement filtrable par export et consultable en requêtant l'API par un timestamp de début et de fin.
* Pour les DELETE, utiliser un trigger qui suit la synthèse et qui log uniquement les DELETE (dans gn_commons.t_history ou une table dédiée avec pareil, `id_synthese`, `uuid`, `ts_delete`). La limite de cela est lors de grosses suppressions mais c'est un trigger léger et qui ne devrait pas avoir de conséquences en perfs au regard des autres actuellement utilisés sur la synthese. Cette API serait aussi consultable en requêtant l'API par un timestamp de début et de fin.

**Comment by camillemonchicourt** [comment]
Oui, on vient aussi d'en discuter avec @amandine-sahl et c'est aussi l'idée que l'on retenait.
Pour éviter les confusions, on parlait de tracer les suppressions de la synthèse dans une table dédiée, donc pas ``gn_commons.t_history`` car ça serait un traçage partiel et spécifique, donc le mettre dans ``gn_commons.t_history`` pourrait apporter de la confusion. D'autant plus qu'on y trace plutôt l'historique des données source.

Et en effet si on trace que les suppressions, alors l'impact de performance nous semblait aussi minime ou peu génant.

**Comment by lpofredc** [comment]
A suivre côté GeoNature. cf. https://github.com/PnX-SI/GeoNature/pull/1456
