### ISSUE TITLE
Bad data errors - Logs and email 

### ISSUE THREAD

**Issue by Adrien-Pajot** [lpoaura/GN2PG#11]
With @[DonovanMaillard](https://github.com/DonovanMaillard) we tried to add data with a cd_nom 'blue'. 
Obviously this could not work :

``` 
Traceback (most recent call last):
  File "/home/geonatureadmin/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/geonatureadmin/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: ERREUR:  syntaxe en entrée invalide pour le type integer : « bleu »
CONTEXT:  fonction PL/pgSQL gn2pg.fct_tri_c_upsert_data_to_geonature_with_cd_nomenclature(), ligne 134 à instruction SQL
``` 
However, we thought that it was good to store all wrong lines in log and to send an email to the source database manager so that it can modify the data directly in its database. 
Therefore, we could add the email in the config file.

**Comment by lpofredc** [comment]
Is that error logged into `error_log` table in db?

Import errors should be logged into that log table which contains various informations:
* source
* id_data (from source)
* controler (concerned table: data, download, etc.)
* last_ts: timestamp
* item: json source data
* error: error message

It would effectively be interesting to identify each full-download or update sessions (uuid?) to futurely add reports features.

**Comment by lpofredc** [comment]
logs stored in the database can now be consulted via the "dashboard" add-on tool. _cf_. https://gn2pg.readthedocs.io/en/latest/dashboard.html
