### ISSUE TITLE
GN2PG limit&offset

### ISSUE THREAD

**Issue by MathildeLeclerc** [lpoaura/GN2PG#13]
Nous avons essayé d'importer des données dans la synthèse de GeoNature à partir d'une API d'un autre GeoNature en utilisant GN2PG. Nous avons constaté que nous téléchargions moins de données dans la base (4 205 données) que le nombre total de données de l'export (7 110). 

En cherchant d'où venait le problème, nous avons remarqué que certaines données étaient manquantes (par rapport aux données contenues dans le csv) et que certaines étaient répétées.

Le problème vient de l'API d'export de GeoNature et plus particulièrement au niveau de la requête avec une limite et offset.
D'après la documentation de Postgresql: https://www.postgresql.org/docs/9.3/queries-limit.html
"When using LIMIT, it is important to use an ORDER BY clause that constrains the result rows into a unique order. Otherwise you will get an unpredictable subset of the query's rows. "

Nous allons donc mettre un ticket sur le module d'export, et essayer de résoudre le problème.

**Comment by MathildeLeclerc** [comment]
https://github.com/PnX-SI/GeoNature/issues/1426

**Comment by lpofredc** [comment]
Déjà intégré depuis la version [1.3.0](https://github.com/lpoaura/GN2PG/releases/tag/1.3.0)
