### ISSUE TITLE
gn2pg_import - error_count donnée en entrée invalide

### ISSUE THREAD

**Issue by DonovanMaillard** [lpoaura/GN2PG#18]
Launching command gn2pg_cli --full myconfigfile, returns synax error (error_count data is not an integer)

sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) ERREUR:  syntaxe en entrée invalide pour le type integer : « data »
LINE 1: ...t, http_status, comment) VALUES ('flaviabase', 0, 'data', 0,...
                                                             ^

[SQL: INSERT INTO gn2pg_import.download_log (source, controler, error_count, http_status, comment) VALUES (%(source)s, %(controler)s, %(error_count)s, %(http_status)s, %(comment)s)]
[parameters: {'source': 'flaviabase', 'controler': 0, 'error_count': 'data', 'http_status': 0, 'comment': 0}]

**Comment by camillemonchicourt** [comment]
Fixed in 0.1.2

**Comment by DonovanMaillard** [comment]
fonctionnel ;) Merci
