### ISSUE TITLE
Nomenclatures - Utiliser les codes plutôt que les labels

### ISSUE THREAD

**Issue by camillemonchicourt** [lpoaura/GN2PG#3]
Actuellement ce sont les labels qui sont utilisés pour retrouver les correspondances des nomenclatures.
Cependant ceci ne sont pas forcément très stables, et parfois modifiés sur une instance GeoNature.
Les codes des nomenclatures sont plus robustes.
De plus ils disposent déjà de leur fonction ``get_id_nomenclature`` (https://github.com/PnX-SI/Nomenclature-api-module/blob/master/data/nomenclatures.sql#L99)

Il faudrait donc plutôt utiliser ces codes plutôt que les labels.
Pour le moment ce sont les labels qui ont été utilisés car ce sont les labels qui sont utilisés dans l'export SINP fourni par défaut dans le module Export de GeoNature.
Cependant il faudrait peut-être privilégier de créer un autre export, éventuellement taillé sur mesure pour GN2GN, qui utiliserait les codes, et serait plus stable dans le temps et dédié aux échanges entre instances GeoNature.

**Comment by lpofredc** [comment]
Oui, totalement d'accord. 

A vrai dire, il est possible de configurer différents types d'imports (et pas que synthèse). Cette appli permet l'import n'importe quel export du module d'export (suffit de spécifier son id et la donnée est téléchargée en bdd, au format json). 

Par défaut, c'est le type est ̀`synthese`. mais l'option `data_type` dans la configuration de la source permet de spécifier n'importe quel autre type. Il suffirait alors ensuite de personnaliser les triggers avec une condition `WHEN new.data_type = '<mondatatype>` pour éxécuter tel ou tel trigger, laissant ainsi de la souplesse dans l'usage (l'appli propose un trigger de base, on pourra étoffer l'offre et l'utilisateur peut aussi très bien en ajouter par lui même. On peut donc ainsi ainsi proposer a minima deux fonctions de triggers pour des exports avec le label nomenclature (ex. `synthese_with_label`) ou avec les cd_nomenclatures (ex. `synthese_with_cdnom`). 

https://github.com/lpoaura/gn2gn_client/blob/f529f9f87bf0faf29b69625b7979a1e4da02fabe/gn2gn/check_conf.py#L81-L83

**Comment by camillemonchicourt** [comment]
OK super.
Oui et donc si besoin, on pourrait créer un import dédié à GN2GN renvoyant les codes des nomenclatures.
A noter en passant, je sais pas si tu les utilises, mais @joelclems et @amandine-sahl ont  créé des fonctions d'import dans la synthèse depuis des json pour l'API Synthèse : https://github.com/PnX-SI/GeoNature/blob/master/data/core/synthese.sql#L1120

**Comment by lpofredc** [comment]
Ok, merci. Oui, j'avais vu ça. ça mériterait en effet d'échanger avec eux pour mieux cerner leur fonctionnement.

**Comment by lpofredc** [comment]
De base, les deux formats sont possibles, la version avec `cd_nomenclature` est évidemment recommandée.
