### ISSUE TITLE
Connection abort on gn_module_export > 1.5

### ISSUE THREAD

**Issue by DonovanMaillard** [lpoaura/GN2PG#47]
Connection abort exception occure after " Successfully logged in into GeoNature" and PARAMS. 

A token have been added on gn_module_export after version 1.5, may be the problem ?

**Comment by camillemonchicourt** [comment]
Pourtant on a aussi gardé l'ancien système d'authentification aux API des exports pour garantir la rétro-compatibilité. 🤔

**Comment by DonovanMaillard** [comment]
Oui, il y a peut-être autre chose, à creuser... 

Je viens de lancer une synchro sur un module d'export "ancienne génération" et ça fonctionne, gn2pg est donc bien opérationnel de mon coté. J'ai donc mis ça sur la nouvelle version et le token... mais peut être un peu trop vite.

J'ai interrogé cette instance avec le module d'export "nouvelle version" sur les 2 URL "/api/export/api/2" et "/api/export/api/2?token=MONTOKEN ", aucun ne marche. Ce n'est donc peut être pas qu'un soucis de token.

J'attends de voir avec Gil qui gère cette instance si on arrive à avoir davantage d'infos et je reviens compléter ici quand on aura trovéu le soucis.

**Comment by lpofredc** [comment]
@DonovanMaillard , pourais-tu fournir un log plus complet (et en utilisant l'option --verbose)?

**Comment by DonovanMaillard** [comment]
Salut @lpofredc , c'était un soucis coté fournisseur, l'API ne retournait rien et renvoyait un time out. 

Gil a pu corriger ce soucis en partie en mettant à jour la dépendance utils-flask-sqlalquemy en 0.3.5 (cf https://github.com/PnX-SI/gn_module_export/issues/197) 

Mais j'ai maintenant un autre soucis déjà relayé ailleurs, avec l'import de 2000 données sur 1000 (200%) et fin de l'upload. Idem si je veux récupérer les données LPO, "No data available from from lpo-aura". A détricoter et voir dans des tickets dédiés donc, pour ce ticket en particulier le time out n'est plus reproduit avec utils-flask-sqlalquemy 0.3.5

**Comment by lpofredc** [comment]
En effet, ce pb de comptage et fin d'upload sont signélés ici https://github.com/lpoaura/GN2PG/issues/48 & là https://github.com/lpoaura/GN2PG/issues/49
