### ISSUE TITLE
informations sur le suivi de l'import erronnées

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/GN2PG#48]
Il y a un pb dans les valeurs affichées

![image](https://github.com/lpoaura/GN2PG/assets/51160496/72ea7b86-95cf-4a8e-b678-049af675153d)

**Comment by lpofredc** [comment]
Erreur causée par Utils-SQLAlchemy utilisé par le module d'export https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/issues/40, fix https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/pull/41

**Comment by camillemonchicourt** [comment]
Corrigé avec la version 0.3.6 de Utils-Flask-SQLAlchemy, intégrée à GN 2.13.1, ou à mettre à jour manuellement.
Voir https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/issues/40
