### ISSUE TITLE
Quel nom pour l'application?

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/GN2PG#5]
Cette application, initialement spécifiquement conçue pour les transfert de données entre instances GeoNature (synthèse à synthèse) s'avère finalement plus générique. 

Le cœur de cette application permet de transférer n'importe quelle données (synthèse mais aussi tout autre données) issues du module d'exports dans une base de données PostgreSQL (GeoNature ou autre). 

Seul le procédé de mise à jour incrémentale sera, pour le moment, spécifique à la synthèse.

De fait, se pose la question de trouver un nom plus proche de la réalité de cette application. nous sommes preneur de toutes idées :smiley:

**Comment by camillemonchicourt** [comment]
GN2TheWorld ! :-D

**Comment by camillemonchicourt** [comment]
Mais sans rire. GN2GN était simple et clair et pas mal adapté à un outil technique.
Mais si on veut élargir, peut-être GN2PG pour rester simple et clair ?

**Comment by lpofredc** [comment]
merci @camillemonchicourt, oui, j'avais justement `gn2pg` en tête. Sinon `xfer_gn` ou `transfer_gn`.

**Comment by camillemonchicourt** [comment]
Ouais je voterai pour GN2PG (en majuscule) plus simple et clair selon moi.

**Comment by lpofredc** [comment]
Done :grin:
