### ISSUE TITLE
GN2GN - Meta_update_date GeoNature synthese

### ISSUE THREAD

**Issue by Adrien-Pajot** [lpoaura/GN2PG#8]
When I imported data from another GeoNature to mine I checked if all variables were logical and I reported :  
![Create and update dates synthese](https://user-images.githubusercontent.com/62794251/116064643-7b561680-a686-11eb-9f8a-783b9bc03745.png)

I launched `gn2pg-cli --full <myconfigfile>` at 2021-04-26 11:48 so the creation date is logical but not the update one. 
As it is the first time this added to my synthesis I suggest to have create and update date identical. Otherwise, we can keep create and update dates as the one in the source GeoNature ?

What do you think ?

**Comment by camillemonchicourt** [comment]
Yes good question.
This field features the "creation_date" in the source database, or in the destination database.
But yes, creation_date and update_date should be consistent.

**Comment by lpofredc** [comment]
Yes, good point. Meta_create_date and Meta_update_date fields in client table "synthese" are now locally generated (with default geonature triggers).
