### ISSUE TITLE
Ajout d'une source gn2pg dans additional_data de CA et JDD

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/GN2PG#87]
### Feature description

Prévoir l'ajout d'une information permettant de connaitre l'origine des métadonnées insérées dans CA et JDD (gn2pg + nom de la source), champ additionel json (additional_data) à peupler.

**Comment by lpofredc** [comment]
Ajout des informations sur le même principe que dans le schéma utilisateurs:
```json
{
  "source":"<nom de la source>",
  "module":"gn2pg",
  ...
}
```
