### ISSUE TITLE
GN2PG - Don't fetch data your already have

### ISSUE THREAD

**Issue by Adrien-Pajot** [lpoaura/GN2PG#9]
GN2PG takes a non negligible time to import data (1h for 60000 in my case). 
Further more, it reaches all the data that are available from the export every time you run it. 

Therefore, it would interesting for GN2PG to fetch data **that have been created or updated after the last valid import** 

As a user and not a developer I suppose that the export must be correctly configured in GeoNature and then API selects only the data with create or update date > last import date. You thus need to store the last complete import date. 

Will be very interesting to automate import every day/week/month between two or more structures !

**Comment by Adrien-Pajot** [comment]
The problem is for deletion. Export should expose data that have been deleted to avoid keeping them.

**Comment by camillemonchicourt** [comment]
See https://github.com/lpoaura/GN2PG/issues/1

**Comment by lpofredc** [comment]
As mentionned by @camillemonchicourt , a work is actually in progress to log history on source database (Create, Update, Delete), see : https://github.com/PnX-SI/GeoNature/compare/develop...lpofredc:log_history

This new incremental update feature will come soon, in next weeks.

**Comment by lpofredc** [comment]
Incremental update now implemented since v0.1.0-dev
